dist: xenial
language: go

branches:
  only:
  - master

git:
  depth: false

services:
  - docker
before_script:
  - CHANGED_FILES_PR=$(git diff --name-only HEAD $(git merge-base HEAD $TRAVIS_BRANCH))
script:
  - set -o pipefail ;
    make ci e2e status=keep 2>&1 | ts '[%H:%M:%.S]' -s
after_success:
  - if [[ "${CHANGED_FILES_PR[@]}" =~ "scripts/kind-e2e/e2e.sh" ]]; then
      echo "scripts/kind-e2e/e2e.sh was modified, testing recurring run on already deployed infrastructure.";
      set -o pipefail ;
      make e2e status=keep | ts '[%H:%M:%.S]' -s;
    fi
deploy:
  - provider: script
    script: bash scripts/release
    on:
      branch: master
  - provider: script
    script: bash scripts/release
    on:
      tags: true
