---
name: Flake Finder

on:
  schedule:
    - cron: "0 0,1 * * *"

jobs:
  e2e:
    name: E2E
    if: github.repository_owner == 'submariner-io'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', 'globalnet']
        deploytool: ['operator', 'helm']
        k8s_version: ['1.23']
        include:
          - k8s_version: '1.21'
          - k8s_version: '1.22'
    steps:
      - name: Check out the repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Run E2E deployment and tests
        uses: submariner-io/shipyard/gh-actions/e2e@release-0.13
        with:
          using: ${{ matrix.deploytool }} ${{ matrix.globalnet }}

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@release-0.13
